// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Credits: typeof import('./src/components/pages/help/credits.vue')['default']
    Dropdown: typeof import('./src/components/common/dropdown.vue')['default']
    Features: typeof import('./src/components/pages/help/features.vue')['default']
    Handle: typeof import('./src/components/pages/help/handle.vue')['default']
    HomePage: typeof import('./src/components/pages/home/home-page.vue')['default']
    Markdown: typeof import('./src/components/common/markdown.vue')['default']
    NavigationBar: typeof import('./src/components/common/navigation-bar.vue')['default']
    NavigationHeader: typeof import('./src/components/common/navigation-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/pages/home/search-bar.vue')['default']
    SearchStatus: typeof import('./src/components/pages/home/search-status.vue')['default']
    SettingsPage: typeof import('./src/components/pages/settings/settings-page.vue')['default']
    StudentItem: typeof import('./src/components/pages/home/student-item.vue')['default']
    StudentList: typeof import('./src/components/pages/home/student-list.vue')['default']
    Switch: typeof import('./src/components/common/switch.vue')['default']
  }
}
