// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/page/help/about.vue')['default']
    Credits: typeof import('./components/page/help/credits.vue')['default']
    Dropdown: typeof import('./components/common/dropdown.vue')['default']
    Features: typeof import('./components/page/help/features.vue')['default']
    Handle: typeof import('./components/page/help/handle.vue')['default']
    ICarbonBarrier: typeof import('~icons/carbon/barrier')['default']
    ICarbonCaretUp: typeof import('~icons/carbon/caret-up')['default']
    ICarbonClose: typeof import('~icons/carbon/close')['default']
    ICarbonHome: typeof import('~icons/carbon/home')['default']
    ICarbonInformation: typeof import('~icons/carbon/information')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSettings: typeof import('~icons/carbon/settings')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    NavigationBar: typeof import('./components/page/common/navigation-bar.vue')['default']
    NavigationHeader: typeof import('./components/page/common/navigation-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/page/home/search-bar.vue')['default']
    Student: typeof import('./components/page/home/student.vue')['default']
    StudentList: typeof import('./components/page/home/student-list.vue')['default']
    Switch: typeof import('./components/common/switch.vue')['default']
  }
}
