// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dropdown: typeof import('./components/common/dropdown.vue')['default']
    ICarbonBarrier: typeof import('~icons/carbon/barrier')['default']
    ICarbonBox: typeof import('~icons/carbon/box')['default']
    ICarbonCaretUp: typeof import('~icons/carbon/caret-up')['default']
    ICarbonClose: typeof import('~icons/carbon/close')['default']
    ICarbonHome: typeof import('~icons/carbon/home')['default']
    ICarbonInformation: typeof import('~icons/carbon/information')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSettings: typeof import('~icons/carbon/settings')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    NavigationBar: typeof import('./components/navigation-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/search-bar.vue')['default']
    Student: typeof import('./components/student.vue')['default']
    StudentList: typeof import('./components/student-list.vue')['default']
    Switch: typeof import('./components/common/switch.vue')['default']
  }
}

export {}
